# How to author Executors: https://circleci.com/docs/2.0/reusing-config/#authoring-reusable-executors
description: >
  Machine executor provided by CircleCI. Needed for privileged access to Docker for the SAM CLI.
machine: true
